// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD6iqgBwP4mNlZgXFFxEMXSeyb29heQmg',
    appId: '1:92635895667:web:0e22a791fcffa260905706',
    messagingSenderId: '92635895667',
    projectId: 'danny-chat-poc',
    authDomain: 'danny-chat-poc.firebaseapp.com',
    storageBucket: 'danny-chat-poc.firebasestorage.app',
    measurementId: 'G-T1MVS69S7E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALNizFQ1lJ_IqaazxAMz8fIyzFuJDitPU',
    appId: '1:92635895667:android:a6b847d8827da222905706',
    messagingSenderId: '92635895667',
    projectId: 'danny-chat-poc',
    storageBucket: 'danny-chat-poc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD56Pr9TFiOMSdE-K6xu1n2BQDwAP97teM',
    appId: '1:92635895667:ios:a0dc787c3a062d1c905706',
    messagingSenderId: '92635895667',
    projectId: 'danny-chat-poc',
    storageBucket: 'danny-chat-poc.firebasestorage.app',
    iosClientId: '92635895667-9big0jbqgtktre2r1pap612ps1kcodus.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD56Pr9TFiOMSdE-K6xu1n2BQDwAP97teM',
    appId: '1:92635895667:ios:a0dc787c3a062d1c905706',
    messagingSenderId: '92635895667',
    projectId: 'danny-chat-poc',
    storageBucket: 'danny-chat-poc.firebasestorage.app',
    iosClientId: '92635895667-9big0jbqgtktre2r1pap612ps1kcodus.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAD6iqgBwP4mNlZgXFFxEMXSeyb29heQmg',
    appId: '1:92635895667:web:8af3d80cc519fd1c905706',
    messagingSenderId: '92635895667',
    projectId: 'danny-chat-poc',
    authDomain: 'danny-chat-poc.firebaseapp.com',
    storageBucket: 'danny-chat-poc.firebasestorage.app',
    measurementId: 'G-T0WDWVD20G',
  );

}